config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'user_books#index'

  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  resources :user_books
  resources :users

  resources :books do
    member do
      get 'delete'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :users, through: :user_books
  has_many :user_books

  validates :title, :author, :published_date, presence: true
  validates :price, presence: true, numericality: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :books, through: :user_books
  has_many :user_books
end

app/models/user_book.rb
# frozen_string_literal: true

class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      admin = Admin.from_google(**from_google_params)
  
      if admin.present?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect admin, event: :authentication
      else
        flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
        redirect_to new_admin_session_path
      end
    end
  
    protected
  
    def after_omniauth_failure_path_for(_scope)
      new_admin_session_path
    end
  
    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end
  
    private
  
    def from_google_params
      @from_google_params ||= {
        uid: auth.uid,
        email: auth.info.email,
        full_name: auth.info.name,
        avatar_url: auth.info.image
      }
    end
  
    def auth
      @auth ||= request.env['omniauth.auth']
    end
  end
  

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
    def after_sign_out_path_for(_resource_or_scope)
      new_admin_session_path
    end
  
    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end
  end
  

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
    before_action :authenticate_admin!
end  

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @books = Book.order(:title)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to(books_path, notice: 'Book was successfully created.')
    else
      flash[:alert] = 'There was an error creating the book.'
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to(book_path(@book), notice: 'Book was successfully updated.')
    else
      flash[:alert] = 'There was an error updating the book.'
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to(books_path, notice: 'Book was successfully deleted.')
  end

  def book_params
    params.require(:book).permit(:title, :author, :price, :published_date)
  end
end

app/controllers/user_books_controller.rb
# frozen_string_literal: true

class UserBooksController < ApplicationController
  before_action :set_user_book, only: %i[show edit update destroy]

  # GET /user_books or /user_books.json
  def index
    @user_books = UserBook.all
  end

  # GET /user_books/1 or /user_books/1.json
  def show; end

  # GET /user_books/new
  def new
    @user_book = UserBook.new
  end

  # GET /user_books/1/edit
  def edit; end

  # POST /user_books or /user_books.json
  def create
    @user_book = UserBook.new(user_book_params)

    respond_to do |format|
      if @user_book.save
        format.html { redirect_to @user_book, notice: 'User book was successfully created.' }
        format.json { render :show, status: :created, location: @user_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_books/1 or /user_books/1.json
  def update
    respond_to do |format|
      if @user_book.update(user_book_params)
        format.html { redirect_to @user_book, notice: 'User book was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_books/1 or /user_books/1.json
  def destroy
    @user_book.destroy

    respond_to do |format|
      format.html { redirect_to user_books_path, status: :see_other, notice: 'User book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_book
    @user_book = UserBook.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_book_params
    params.require(:user_book).permit(:user_id, :book_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/helpers/user_books_helper.rb
# frozen_string_literal: true

module UserBooksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/books/_flash.html.erb
<% flash.each do |key, message| %>
    <div class="flash <%= key %>">
      <%= message %>
    </div>
<% end %>

app/views/books/_form.html.erb
<table summary="Book form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field :title %></td>
  </tr>
  <tr>
    <th>Author</th>
    <td><%= f.text_field :author %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.number_field :price, step: 0.01 %></td>
  </tr>
  <tr>
    <th>Published Date</th>
    <td>
      <%= f.date_select :published_date, start_year: 1900, end_year: Time.now.year %>
    </td>
  </tr>
</table>

app/views/books/delete.html.erb
<%= link_to('Back to Homepage', {controller: 'books', action: 'index'}) %><br />

<div class="books delete">
  <h2>Delete a Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>
    <% # url: book_path(@book), method: 'delete' %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to('Back to Homepage', {controller: 'books', action: 'index'}) %><br />

<div class="books edit">
  <h2>Update a Book</h2>

  <%= form_for(@book) do |f| %>
    <% # url: book_path(@book), method: 'patch' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Update book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<%= link_to('Back to Homepage', {controller: 'books', action: 'index'}) %><br />

<div class="books index">
  <h2>Book Collection</h2>

  <!-- Flash messages -->
  <%= render "flash" if flash.any? %>

  <%= link_to("Add New Book", new_book_path, class: 'action new') %>

  <table class="listing" summary="Book list" style="width: 100%;">
    <tr class="header">
      <th style="text-align: left;">Title</th>
      <th style="text-align: left;">Author</th>
      <th style="text-align: left;">Price</th>
      <th style="text-align: left;">Published Date</th>
      <th style="text-align: left;">Actions</th>
    </tr>

    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.price %></td>
      <td><%= book.published_date %></td>
      
      <td class="actions">
        <%= link_to("Show", book_path(book), class: 'action show') %>
        <%= link_to("Edit", edit_book_path(book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= link_to('Back to Homepage', {controller: 'books', action: 'index'}) %><br />

<div class="books new">
  <h2>Add a Book</h2>

  <!-- Flash Messages -->
  <% flash.each do |key, message| %>
    <div class="flash <%= key %>">
      <p><%= message %></p>
    </div>
  <% end %>

  <!-- Form for Adding a New Book -->
  <%= form_for(@book) do |f| %>
    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create book") %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to('Back to Homepage', {controller: 'books', action: 'index'}) %><br />

<div class="books show">
  <h2>Show book</h2>

  <table summary="Book detail view">
    <tr class="header">
      <th style="text-align: left;">Title</th>
      <th style="text-align: left;">Actions</th>
    </tr>
    
    <tr>
      <td><%= @book.title %></td>

      <td class="actions">
        <%= link_to("Edit", edit_book_path(@book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(@book), class: 'action delete') %>
      </td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "BookCollection" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/user_books/_form.html.erb
<%= form_with(model: user_book) do |form| %>
  <% if user_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_book.errors.count, "error") %> prohibited this user_book from being saved:</h2>

      <ul>
        <% user_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, User.order(:username).map { |user| [user.username, user.id] }, include_blank: true, id: "id_of_the_user_id_select_box" %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.select :book_id, Book.order(:title).map { |book| [book.title, book.id] }, include_blank: true, id: "id_of_the_book_id_select_box" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_books/edit.html.erb
<h1>Editing User Book</h1>

<%= render 'form', user_book: @user_book %>

<%= link_to 'Show', @user_book %> |
<%= link_to 'Back', user_books_path %>

app/views/user_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Books</h1>
<h2>This is the authenticated version 2</h2>

<h3>You're logged in! Welcome to the Dashboard!</h3>
<%= link_to "Sign Out", destroy_admin_session_path %>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Book Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_books.each do |user_book| %>
      <tr>
        <td><%= User.where(id: user_book.user_id).last.username %></td>
        <td><%= Book.where(id: user_book.book_id).last.title %></td>
        <td><%= link_to 'Show', user_book %></td>
        <td><%= link_to 'Edit', edit_user_book_path(user_book) %></td>
        <td><%= link_to 'Destroy', user_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Book', new_user_book_path %>

<br>

<%= link_to 'Book index', books_path %>

<br>

<%= link_to 'User index', users_path %>

app/views/user_books/new.html.erb
<h1>New User Book</h1>

<%= render 'form', user_book: @user_book %>

<%= link_to 'Back', user_books_path %>

app/views/user_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_book.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @user_book.book_id %>
</p>

<%= link_to 'Edit', edit_user_book_path(@user_book) %> |
<%= link_to 'Back', user_books_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>